---
output: pdf_document
geometry: margin = 1in
---


## Zusammenfassung

Wir befinden uns in einem Zeitalter, in dem immer mehr Anwendungsbereiche für maschinelles Lernen gefunden werden. Auch im Bereich der Finanzen werden die Möglichkeiten erforscht. Im Gegensatz zu einer einfachen Methode wie der linearen Regression sind Deep-Learning-Methoden jedoch recht komplex und für potenzielle Investoren oft nicht greifbar. Diese Arbeit beschäftigt sich mit der Anwendung von neuronalen Netzen, deren Erklärbarkeit (Explainable Artificial Intelligence, XAI) und dem Trading von Bitcoin. Es wird die Theorie der verwendeten neuronalen Netze und der neuartige Aspekt der XAI erläutert, außerdem gibt es einen kurzen Einblick in die Bitcoin-Theorie. Wir orientieren uns an der Autokorrelation der Log-Renditen, um einen geeigneten Input-Layer zu definieren. Die optimale Anzahl der Hidden-Layer und Neuronen wird dann durch den quantitativen Vergleich der Fehlerfunktion MSE und der Sharpe Ratio für jede mögliche Kombination bestimmt. Eine XAI-Anwendung, Linear Parameter Data (LPD), wird verwendet, um zu bestimmen, in welchen Phasen das neuronale Netzwerk zuverlässig ist. Kombiniert mit einer Volatilitätsvorhersage aus einem GARCH-Modell wird eine Tradingstrategie implementiert und mit dem Hinzufügen der Kryptowährung Ether verbessert. Die Ergebnisse sind vielversprechend, da die Einbeziehung von LPD zu einem Mehrwert im Rahmen dieser Bachelorarbeit führt. Darüber hinaus ermöglicht das Hinzufügen von Trades, welche auf Ether basieren, sogar eine bessere Performance als eine reine Buy-and-Hold Strategie.