---
output: pdf_document
geometry: margin = 1in
---

## 1. Introduction {#introduction}

The well-known asset classes such as equities, bonds, and money market instruments have existed for several decades and have established themselves as a fixed component in many portfolios. The approach often taken is that, in principle, the equity component is responsible for the main return and the remaining asset classes are used to optimize the risk/return ratio. Recently, there has been much discussion about a new asset class that has a low correlation to the equity markets, very high volatility, but also enormous opportunities for profit [@bitcoin_market]. The best-known cryptocurrency with the largest market capitalization at the moment is Bitcoin (BTC). Compared to traditional asset classes, the characteristics of the Bitcoin market are relatively unexplored. Especially for the reason that only about ten years of historical data is available for Bitcoin. In addition to this aspect, the costs for trading Bitcoin are surprisingly low and are in the per mille range when using exchanges like Binance or Kraken. These characteristics make Bitcoin an attractive investment vehicle to test the application of artificial neural networks. In this sense, this thesis investigates how the use of feedforward neural networks with their non-linear properties can be used to build a profitable trading strategy. Three central questions are pursued:

1) How does the selection of the network architecture influence the quality of predictions? What influence can be found concerning the Sharpe ratio of a simple trading strategy?

2) What is the added value of enhancing this neural network with aspects of Explainable Artificial Intelligence (XAI)? 

3) How can the acquired information about neural networks, XAI, and general time series analysis be used to define an efficient trading strategy?

To investigate these aspects, the first step is trying to find an optimal network architecture. For this purpose, all possible combinations between the simplest model (one layer and one neuron) and the most complex model (three layers with ten neurons each) are tested and the results quantified using the common error function Mean Squared Error (MSE) and the Sharpe ratio. Unlike linear regression, the neural network cannot be intuitively explained by the partial effects because it behaves non-linearly. Therefore, the Linear Parameter Data (LPD) method is used to investigate how the network behaves with input stimuli. Furthermore, the volatility clusters, typical for financial time series are investigated and evaluated with a simple GARCH model. The basic assumption is that the Bitcoin market, like stock markets, behaves asymmetrically. This phenomenon describes the tendency of market volatility to be higher in declining markets than in rising markets. As a further idea, it is suggested to exit the long position in certain phases and to switch to Ether (ETH) as an alternative investment instrument. These aspects are combined and defined as a trading strategy. 

We believe that the examination of neural networks in the field of (crypto-)finance is of great importance. The benefits of deep learning have already been proven in many applications outside this field. Ever since Siri was launched by Apple Inc. in 2011, people outside the world of science have begun to have a rough idea of what artificial intelligence is. Although the application of neural networks in the use case of Siri and Natural Language Processing (NLP) seems reasonable, the opinion is divided regarding the application in the field of financial time series. Since most movements of financial instruments are based on white noise and thus have almost no dependency structure, the implementation of a meaningful method is challenging. Likewise, integration of neural networks only makes sense if a comprehensible and systematically replicable overperformance can be achieved. This bachelor thesis deals exactly with this topic. The application of neural networks for the prediction and trading of Bitcoin is investigated. Aspects of XAI and volatility modeling are included to possibly shed some light on this black box. 