---
output: pdf_document
geometry: margin = 1in
---

## 2. Theory

### 2.1. Neural Network

Set of algorithms to recognize pattern. Mapping input to output.
Three different applications

- Classification (Supervised Learning): Depending on labeled data (Human groups them, or result of another method). NN finds correlation between labels and data. -> **identify objects in imgs, gesture recognition, detect voices, classify text as spam**
- Clustering (Unsupervised Learning): Detection of similarities, grouping them together. Unlabeled data. The more data, the more accurate is the output. -> **fraud detection, comparing docs/imgs, anomaly detection**
- Predictive Analysis: Exposed to enough data, NN is able to establish correlation between present events and future events. Regression between the past and the future. -> **Time Series, predict the number which most likely to occur next**

Further explanation: Nodes, Layer, Input, Ouput, Weights, Activation funtion, Training, Feedforward NN, Mulitple linear Regression, Gradient Descent, Logistic Regression

### 2.2. LSTM / RNN

Long-short-term-memory / Recurrent Neural Networks

Explain.

### 2.3. Bitcoin

#### 2.3.1. SHA256 Hash

- Block
- Blockchain
- Distributed Blockchain
- Token
- Coinbase Transaction
- Public/Private Key -> Signing
- Signature (sign, verify)
- Transaction

