---
output: pdf_document
geometry: margin = 1in
---

## 5. Conclusion

Best Trading Algorithm ever!

### 5.1. Get rich or die tryin

Neque volutpat ac tincidunt vitae semper quis. At elementum eu facilisis sed odio morbi quis commodo odio. Eget dolor morbi non arcu risus quis. Gravida quis blandit turpis cursus in hac. Vehicula ipsum a arcu cursus vitae congue mauris. Id eu nisl nunc mi ipsum faucibus vitae. Ut sem viverra aliquet eget sit amet. Tempor orci eu lobortis elementum. Eu feugiat pretium nibh ipsum consequat nisl vel pretium. Vel turpis nunc eget lorem dolor sed viverra. Enim neque volutpat ac tincidunt. Eget nullam non nisi est sit amet facilisis magna. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Diam vel quam elementum pulvinar etiam non. In hac habitasse platea dictumst vestibulum rhoncus. Mattis aliquam faucibus purus in massa. Netus et malesuada fames ac. In fermentum posuere urna nec tincidunt praesent. Dolor sit amet consectetur adipiscing. At in tellus integer feugiat scelerisque.

### 5.2. Be GME stock, or not to be GME stock

Tellus at urna condimentum mattis pellentesque id nibh. Morbi tempus iaculis urna id volutpat lacus laoreet. Sem fringilla ut morbi tincidunt augue interdum. Mauris nunc congue nisi vitae. Diam maecenas ultricies mi eget. Vel quam elementum pulvinar etiam. Aliquam faucibus purus in massa. In est ante in nibh mauris cursus. Non diam phasellus vestibulum lorem sed risus ultricies. Sed vulputate mi sit amet mauris commodo quis imperdiet massa. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Elit duis tristique sollicitudin nibh sit amet commodo. A iaculis at erat pellentesque adipiscing commodo elit. Quam viverra orci sagittis eu volutpat odio facilisis. Eros donec ac odio tempor orci dapibus ultrices in iaculis.

