# all libraries 
library(xts)
library(PerformanceAnalytics)
library(kableExtra)
library(quantmod)
library(forecast)
library(fGarch)
library(devtools)
library(TTR)
library(neuralnet)
library(boot)
library(MASS)
library(retry) # exception handling in neuralnet
library(lubridate)
library(rugarch)
library(tikzDevice)
library(MASS)
library(latex2exp)
library(DiagrammeR)

