# all libraries 
library(xts)
library(PerformanceAnalytics)
library(kableExtra)
library(quantmod)
library(forecast)
library(fGarch)
library(devtools)
#library(MDFA)
library(neuralnet)
#library(neuralnet)
library(boot)
#library(plyr) 
library(MASS)

