# all libraries 
library(xts)
library(PerformanceAnalytics)
library(kableExtra)
library(dplyr)
library(quantmod)
library(forecast)
library(fGarch)
library(devtools)
library(MDFA)
library(neuralnet)
library(boot)
library(plyr) 
library(MASS)
